services:
  giropops-senhas:
    image: nataliagranato/senhas:056bd-20240826194022 #trocar para imagem a ser criada com APKO
    ports:
      - "5000:5000"
    networks:
      - net-senhas-aleatorias
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis
    ports: "6379:6379"
    networks:
      - net-senhas-aleatorias
networks:
  net-giropops-senhas
    driver: bridge


      